#release configuration
#Wed May 13 06:54:43 CEST 2026
completedPhase=check-poms
exec.activateProfiles=general,artifactory-corp
exec.additionalArguments=-Daether.connector.basic.parallelPut\=false
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.org.apache.sling\:org.apache.sling.junit.core.connection=scm\:git\:https\://gitbox.apache.org/repos/asf/sling-org-apache-sling-junit-core.git
project.scm.org.apache.sling\:org.apache.sling.junit.core.developerConnection=scm\:git\:https\://gitbox.apache.org/repos/asf/sling-org-apache-sling-junit-core.git
project.scm.org.apache.sling\:org.apache.sling.junit.core.tag=HEAD
project.scm.org.apache.sling\:org.apache.sling.junit.core.url=https\://github.com/apache/sling-org-apache-sling-junit-core.git
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=OddEvenVersionPolicy
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://gitbox.apache.org/repos/asf/sling-org-apache-sling-junit-core.git
